### ISSUE TITLE
Disenio de la interfaz principal

### ISSUE THREAD

**Issue by jglezt** [helojagt/Proyecto-Final-Matematicas-Discretas#3]
Tenemos que diseniar una interfas que se vea bien, que muestre lo minimo para funcionar pero que, si lo requiere el usuario, pueda mostrar mas opciones.
Esto es lo principal:
1.  Hacer un programa que reciba como entrada un sistema de ecuaciones.
2.  Al terminar de introducir los datos debe mostrarla y dar la opción de corregir datos.
4. Debe mostrar cada paso del algoritmo.

**Comment by ivanrm95** [comment]
ola
